// ═══════════════════════════════════════════════════════════
//  LEO DISTRICT 306 D1 — DEFAULT SEED DATA
// ═══════════════════════════════════════════════════════════

const SEED_COUNCIL = [
  // Executives
  { id: 'c-e1', name: 'Leo Lion Vinuk Thismalpola', role: 'District President', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 1, tag: 'Executive', icon: 'fa-crown', photo: null, priority: true },
  { id: 'c-e2', name: 'Leo Lion Yashika Rodrigo', role: 'Immediate Past District President', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 2, tag: 'Executive', icon: 'fa-medal', photo: null },
  { id: 'c-e3', name: 'Leo Lion Manish Perera', role: 'District Vice President', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 3, tag: 'Executive', icon: 'fa-user-tie', photo: null },
  { id: 'c-e4', name: 'Lion Suranjani Wickramarathne', role: 'District Leo Chairperson', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 4, tag: 'Executive', icon: 'fa-shield-halved', photo: null },
  { id: 'c-e5', name: 'Leo Hashini Nethmika', role: 'District Secretary', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 5, tag: 'Executive', icon: 'fa-file-pen', photo: null },
  { id: 'c-e6', name: 'Leo Bathisha Kavinda', role: 'District Treasurer', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 6, tag: 'Executive', icon: 'fa-coins', photo: null },
  { id: 'c-e7', name: 'Leo Sanduni Theekshana', role: 'District Membership Chairperson', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 7, tag: 'Executive', icon: 'fa-users-gear', photo: null },
  { id: 'c-e8', name: 'Leo Lion Prabhavee Mayasha', role: 'District Assistant Secretary', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 8, tag: 'Executive', icon: 'fa-file-pen', photo: null },
  { id: 'c-e9', name: 'Leo Dulari Christopher', role: 'District Assistant Secretary', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 9, tag: 'Executive', icon: 'fa-file-pen', photo: null },
  { id: 'c-e10', name: 'Leo Lion Chamal Pramod', role: 'District Assistant Treasurer', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 10, tag: 'Executive', icon: 'fa-coins', photo: null },
  { id: 'c-e11', name: 'Leo Oshadha Tharusha', role: 'District Assistant Treasurer', type: 'exec', year: '2026/2027', status: 'Published', displayOrder: 11, tag: 'Executive', icon: 'fa-coins', photo: null },
  
  // Chiefs
  { id: 'c-c1', name: 'Leo Lion Randiv De Silva', role: 'Chief Council Coordinator', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 12, tag: 'Chief', icon: 'fa-sitemap', photo: null },
  { id: 'c-c2', name: 'Leo Lion Kasun Sapumohotti', role: 'Chief Regional Coordinator', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 13, tag: 'Chief', icon: 'fa-map-location-dot', photo: null },
  { id: 'c-c3', name: 'Leo Kulindu Thenuka Bopage', role: 'Chief Operational Coordinator', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 14, tag: 'Chief', icon: 'fa-gears', photo: null },
  { id: 'c-c4', name: 'Leo Savidya Ranawaka', role: 'Chief Performance Coordinator', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 15, tag: 'Chief', icon: 'fa-chart-line', photo: null },
  { id: 'c-c5', name: 'Leo Lion Senuth Dilnada Wanniarachchi', role: 'Chief IT & Strategic Coordinator', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 16, tag: 'Chief', icon: 'fa-microchip', photo: null },
  { id: 'c-c6', name: 'Leo Lion Dinath Wijesooriya', role: 'Chief Public Relations & Branding Coordinator', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 17, tag: 'Chief', icon: 'fa-bullhorn', photo: null },
  { id: 'c-c7', name: 'Leo Lion Uvini Imalna', role: 'Chief Editor', type: 'chief', year: '2026/2027', status: 'Published', displayOrder: 18, tag: 'Chief', icon: 'fa-pen-nib', photo: null },

  // Directors
  { id: 'c-d1', name: 'Leo Dewmi Tharunya', role: 'Regional Director - Region A', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 19, tag: 'Region A', icon: 'fa-map', photo: null },
  { id: 'c-d2', name: 'Leo Hiruni Fernando', role: 'Regional Director - Region B', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 20, tag: 'Region B', icon: 'fa-map', photo: null },
  { id: 'c-d3', name: 'Leo Nadeesha Mayomi Ekanayaka', role: 'Zonal Director - Zone A1', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 21, tag: 'Zone A1', icon: 'fa-location-dot', photo: null },
  { id: 'c-d4', name: 'Leo Udara Nawarathna', role: 'Zonal Director - Zone A2', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 22, tag: 'Zone A2', icon: 'fa-location-dot', photo: null },
  { id: 'c-d5', name: 'Leo Vihanga Kothalawala', role: 'Zonal Director - Zone B1', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 23, tag: 'Zone B1', icon: 'fa-location-dot', photo: null },
  { id: 'c-d6', name: 'Leo Meuni Liyanage', role: 'Zonal Director - Zone B2', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 24, tag: 'Zone B2', icon: 'fa-location-dot', photo: null },
  { id: 'c-d7', name: 'Leo Sudam Jayawardana', role: 'Co-Head - District Service Committee', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 25, tag: 'Service', icon: 'fa-hands-helping', photo: null },
  { id: 'c-d8', name: 'Leo Treveen Rozairo', role: 'Co-Head - District Service Committee', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 26, tag: 'Service', icon: 'fa-hands-helping', photo: null },
  { id: 'c-d9', name: 'Leo Thenuji Jayakody', role: 'Head - District Talent Committee', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 27, tag: 'Talent', icon: 'fa-star', photo: null },
  { id: 'c-d10', name: 'Leo Lithira Kalubowila', role: 'Head - District Sports Committee', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 28, tag: 'Sports', icon: 'fa-trophy', photo: null },
  { id: 'c-d11', name: 'Leo Buddika Ashan', role: 'Head - IT and Infastructure Committee', type: 'directors', year: '2026/2027', status: 'Published', displayOrder: 29, tag: 'IT', icon: 'fa-server', photo: null },

  // Officers
  { id: 'c-o1', name: 'Leo Damthula Thennakoon', role: 'District Council Officer - Administration Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 30, tag: 'Admin', icon: 'fa-clipboard-user', photo: null },
  { id: 'c-o2', name: 'Leo Sachithra Jalitha', role: 'District Council Officer - Administration Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 31, tag: 'Admin', icon: 'fa-clipboard-user', photo: null },
  { id: 'c-o3', name: 'Leo Ravindu Rajapaksha', role: 'District Council Officer - Sports Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 32, tag: 'Sports', icon: 'fa-trophy', photo: null },
  { id: 'c-o4', name: 'Leo Dasith Damsara', role: 'District Council Officer - Talent Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 33, tag: 'Talent', icon: 'fa-star', photo: null },
  { id: 'c-o5', name: 'Leo Senuth Abeyrathne', role: 'District Council Officer - Talent Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 34, tag: 'Talent', icon: 'fa-star', photo: null },
  { id: 'c-o6', name: 'Leo Saduni Kavindya Ra', role: 'District Council Officer - Editorial Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 35, tag: 'Editorial', icon: 'fa-pen-nib', photo: null },
  { id: 'c-o7', name: 'Leo Chalusha Saveekshana', role: 'District Council Officer - Editorial Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 36, tag: 'Editorial', icon: 'fa-pen-nib', photo: null },
  { id: 'c-o8', name: 'Leo Lion Nethul Trevor', role: 'District Council Officer - IT and Infastructure Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 37, tag: 'IT', icon: 'fa-server', photo: null },
  { id: 'c-o9', name: 'Leo Lion Sanuja Dissanayake', role: 'District Council Officer - IT and Infastructure Committee', type: 'officers', year: '2026/2027', status: 'Published', displayOrder: 38, tag: 'IT', icon: 'fa-server', photo: null }
];

const SEED_PROJECTS = [
  { id: 'p-1', title: 'Alpha One Service Summit', category: 'youth', chairperson: 'Leo Lion Vinuk Thismalpola', organizingCommittee: 'District Executive Board', desc: 'Empowering next-generation leaders with advanced leadership skills, team challenges, and active community development workshops.', objectives: 'Develop leadership capability, train executive members, build network bridges.', date: '2026-07-15', time: '09:00 AM', venue: 'Colombo Royal College Hall', status: 'Ongoing', coverImage: null, registrationLink: '#', reportLink: '', partnerOrganizations: 'Lions District 306 D1', displayOrder: 1, publicationStatus: 'Published' },
  { id: 'p-2', title: 'Genesis One Eco-Initiative', category: 'environment', chairperson: 'Leo Lion Yashika Rodrigo', organizingCommittee: 'Green Service Taskforce', desc: 'Rejuvenating green urban areas, planting native trees, and implementing school gardens for biodiversity education.', objectives: 'Plant 2,500 native trees, educate kids on ecosystem values.', date: '2026-06-10', time: '08:00 AM', venue: 'Gampaha Botanical Zone', status: 'Completed', coverImage: null, registrationLink: '', reportLink: '#', partnerOrganizations: 'Ministry of Environment', displayOrder: 2, publicationStatus: 'Published' },
  { id: 'p-3', title: 'Connect One Digital Classrooms', category: 'vision', chairperson: 'Leo Lion Manish Perera', organizingCommittee: 'IT and Strategy Wing', desc: 'Connecting rural school students with state-of-the-art computers, interactive screens, and e-learning resources.', objectives: 'Equip 10 rural schools with computing resources.', date: '2026-08-20', time: '10:00 AM', venue: 'Rambukkana Public School', status: 'Upcoming', coverImage: null, registrationLink: '#', reportLink: '', partnerOrganizations: 'Intel Sri Lanka', displayOrder: 3, publicationStatus: 'Published' },
  { id: 'p-4', title: 'Pioneer One Mobile Eye Clinic', category: 'vision', chairperson: 'Lion Suranjani Wickramarathne', organizingCommittee: 'District Healthcare Unit', desc: 'Deploying medical testing equipment, diagnosing vision complications, and donating custom reading spectacles.', objectives: 'Screen 1,200 rural residents, distribute 500 spectacles.', date: '2026-05-12', time: '07:30 AM', venue: 'Galle Heritage Community Hall', status: 'Completed', coverImage: null, registrationLink: '', reportLink: '#', partnerOrganizations: 'Sight First Foundation', displayOrder: 4, publicationStatus: 'Published' }
];

const SEED_PRESIDENTS = [
  { id: 'pr-1', name: 'Leo Lion Anju Gayathri', clubName: 'Leo Club of Colombo Host', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 111 2222', email: 'anju@colombohostleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Focused on creating automated data tools for school literacy development.', status: 'Active', displayOrder: 1, photo: null },
  { id: 'pr-2', name: 'Leo Vinuthi Thisansa', clubName: 'Leo Club of Colombo Millenium', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 222 3333', email: 'vinuthi@colombomillenniumleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Driving educational equity campaigns and organizing regional youth talent workshops.', status: 'Active', displayOrder: 2, photo: null },
  { id: 'pr-3', name: 'Leo Sathmi Dinethra', clubName: 'Leo Club of Colombo Six New Stars', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 333 4444', email: 'sathmi@colombosixstars.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Fostering multi-generational heritage conservation and health camp drives.', status: 'Active', displayOrder: 3, photo: null },
  { id: 'pr-4', name: 'Leo Sasun Wijeratne', clubName: 'Leo Club of UOC Alumni', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 444 5555', email: 'sasun@uocalumnileos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Reuniting graduates for sustainable development goals.', status: 'Active', displayOrder: 4, photo: null },
  { id: 'pr-5', name: 'Leo Sajeetharan Mahadevan', clubName: 'Leo Club of University of Colombo Faculty of Science', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 555 6666', email: 'sajeetharan@uocscienceleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Promoting science communication and science outreach programs.', status: 'Active', displayOrder: 5, photo: null },
  { id: 'pr-6', name: 'Leo Vimukthi Rukshika', clubName: 'Leo Club of University of Colombo Faculty of Arts', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 666 7777', email: 'vimukthi@uocartsleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Passionate about structural policy edits and community engagement.', status: 'Active', displayOrder: 6, photo: null },
  { id: 'pr-7', name: 'Leo Yoshani Madhurangi', clubName: 'Leo Club of UOC FOA Alumni', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 777 8888', email: 'yoshani@uocfoaalumnileos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Coordinating large-scale alumni service operations.', status: 'Active', displayOrder: 7, photo: null },
  { id: 'pr-8', name: 'Leo Lion Sithuli Amunuthuduwa', clubName: 'Leo Club of Informatics Institute of Technology', position: 'Club President', year: '2026/2027', region: 'Region A', phone: '+94 77 888 9999', email: 'sithuli@iitleoclub.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Encouraging girls in STEM and tech service project creation.', status: 'Active', displayOrder: 8, photo: null },
  { id: 'pr-9', name: 'Leo Lion Nuran Nayanajith', clubName: 'Leo Club of Moratuwa', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 999 0000', email: 'nuran@moratuwaleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Passionate about water purification systems and rural development.', status: 'Active', displayOrder: 9, photo: null },
  { id: 'pr-10', name: 'Leo Senuja Kaluarachchi', clubName: 'Leo Club of Moratuwa Rathmalana', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 000 1111', email: 'senuja@moratuwarathmalanaleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Engaged in medical screening and public sanitation systems.', status: 'Active', displayOrder: 10, photo: null },
  { id: 'pr-11', name: 'Leo Lion Pumudu Ramuditha', clubName: 'Leo Club of Moratuwa 2020', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 111 3333', email: 'pumudu@moratuwa2020leos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Committed to recycling operations and waste management campaigns.', status: 'Active', displayOrder: 11, photo: null },
  { id: 'pr-12', name: 'Leo Minindu Witharana', clubName: 'Leo Club of Mount Lavinia Orient Centennial', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 222 4444', email: 'minindu@mountlaviniaorientleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Focused on child education and health camps.', status: 'Active', displayOrder: 12, photo: null },
  { id: 'pr-13', name: 'Leo Lion Geemeth Bodiyabadu', clubName: 'Leo Club of Royal Achievers', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 333 5555', email: 'geemeth@royalachieversleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Coordinating vision screening camps and welfare distributions.', status: 'Active', displayOrder: 13, photo: null },
  { id: 'pr-14', name: 'Leo Mihin Senarathna', clubName: 'Leo Club of Kothalawala Defense University', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 444 6666', email: 'mihin@kduleoclub.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Focused on disaster response drills and physical wellness campaigns.', status: 'Active', displayOrder: 14, photo: null },
  { id: 'pr-15', name: 'Leo Randidu Jayawardena', clubName: 'Leo Club of Prince of Wales', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 555 7777', email: 'randidu@princeofwalesleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Organizing school support drives and sports training courses.', status: 'Active', displayOrder: 15, photo: null },
  { id: 'pr-16', name: 'Leo Vinuri Aponso', clubName: 'Leo Club of Princess of Wales', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 666 8888', email: 'vinuri@princessofwalesleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Organizing child care camps and medical tests.', status: 'Active', displayOrder: 16, photo: null },
  { id: 'pr-17', name: 'Leo Danidu Damsith', clubName: 'Leo Club of Sri Sumangala College', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 777 9999', email: 'danidu@srisumangalaleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Coordinating village support projects and welfare events.', status: 'Active', displayOrder: 17, photo: null },
  { id: 'pr-18', name: 'Leo Ometh Nethsanda', clubName: 'Leo Club of Kalutara Vidyalaya', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 888 0000', email: 'ometh@kalutaravidyalayaleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Committed to green initiatives and emergency relief operations.', status: 'Active', displayOrder: 18, photo: null },
  { id: 'pr-19', name: 'Leo Sethmi Sonaya', clubName: 'Leo Club of Kalutara Balika Vidyalaya', position: 'Club President', year: '2026/2027', region: 'Region B', phone: '+94 77 999 1111', email: 'sethmi@kalutarabalikaleos.org', facebook: '#', instagram: '#', linkedin: '#', bio: 'Committed to child development and village support camps.', status: 'Active', displayOrder: 19, photo: null }
];

const SEED_CLUBS = [
  { id: 'cl-1', name: 'Leo Club of Colombo Host', sponsor: 'Lions Club of Colombo Host', region: 'Region A', members: 30, president: 'Leo Lion Anju Gayathri', secretary: 'Leo A. Perera', treasurer: 'Leo B. Perera', advisor: 'Lion C. Perera', charteredDate: '2010-06-01', email: 'colombohostleos@gmail.com', phone: '+94 77 111 2222', facebook: '#', instagram: '#', linkedin: '#', desc: 'Active club hosting community relief and development campaigns.', status: 'Active', displayOrder: 1, logo: null, banner: null },
  { id: 'cl-2', name: 'Leo Club of Colombo Millenium', sponsor: 'Lions Club of Colombo Millenium', region: 'Region A', members: 25, president: 'Leo Vinuthi Thisansa', secretary: 'Leo D. Silva', treasurer: 'Leo E. Silva', advisor: 'Lion F. Silva', charteredDate: '2015-08-01', email: 'colombomillenniumleos@gmail.com', phone: '+94 77 222 3333', facebook: '#', instagram: '#', linkedin: '#', desc: 'Focusing on community healthcare, child health camp designs, and environmental restoration.', status: 'Active', displayOrder: 2, logo: null, banner: null },
  { id: 'cl-3', name: 'Leo Club of Colombo Six New Stars', sponsor: 'Lions Club of Colombo Six New Stars', region: 'Region A', members: 20, president: 'Leo Sathmi Dinethra', secretary: 'Leo G. Perera', treasurer: 'Leo H. Perera', advisor: 'Lion I. Perera', charteredDate: '2020-10-12', email: 'colombosixstars@gmail.com', phone: '+94 77 333 4444', facebook: '#', instagram: '#', linkedin: '#', desc: 'A youth force committed to service, visual aid camps, and social leadership.', status: 'Active', displayOrder: 3, logo: null, banner: null },
  { id: 'cl-4', name: 'Leo Club of UOC Alumni', sponsor: 'Lions Club of Galkissa', region: 'Region A', members: 45, president: 'Leo Sasun Wijeratne', secretary: 'Leo J. Perera', treasurer: 'Leo K. Perera', advisor: 'Lion L. Perera', charteredDate: '2018-04-15', email: 'uocalumnileos@gmail.com', phone: '+94 77 444 5555', facebook: '#', instagram: '#', linkedin: '#', desc: 'Empowering university graduates to stay connected and serve rural communities.', status: 'Active', displayOrder: 4, logo: null, banner: null },
  { id: 'cl-5', name: 'Leo Club of University of Colombo Faculty of Science', sponsor: 'Lions Club of Wellawatta', region: 'Region A', members: 60, president: 'Leo Sajeetharan Mahadevan', secretary: 'Leo M. Perera', treasurer: 'Leo N. Perera', advisor: 'Lion O. Perera', charteredDate: '2012-07-22', email: 'uocscienceleos@gmail.com', phone: '+94 77 555 6666', facebook: '#', instagram: '#', linkedin: '#', desc: 'A science faculty-based club driving technological education and green innovations.', status: 'Active', displayOrder: 5, logo: null, banner: null },
  { id: 'cl-6', name: 'Leo Club of University of Colombo Faculty of Arts', sponsor: 'Lions Club of Colombo New Century Titans', region: 'Region A', members: 50, president: 'Leo Vimukthi Rukshika', secretary: 'Leo P. Perera', treasurer: 'Leo Q. Perera', advisor: 'Lion R. Perera', charteredDate: '2014-09-18', email: 'uocartsleos@gmail.com', phone: '+94 77 666 7777', facebook: '#', instagram: '#', linkedin: '#', desc: 'Engaged in social integration, culture sharing, and language literacy drives.', status: 'Active', displayOrder: 6, logo: null, banner: null },
  { id: 'cl-7', name: 'Leo Club of UOC FOA Alumni', sponsor: 'Lions Club of Colombo New Century Titans', region: 'Region A', members: 30, president: 'Leo Yoshani Madhurangi', secretary: 'Leo S. Perera', treasurer: 'Leo T. Perera', advisor: 'Lion U. Perera', charteredDate: '2019-11-05', email: 'uocfoaalumnileos@gmail.com', phone: '+94 77 777 8888', facebook: '#', instagram: '#', linkedin: '#', desc: 'Reuniting arts graduates to collaborate on societal welfare and youth education.', status: 'Active', displayOrder: 7, logo: null, banner: null },
  { id: 'cl-8', name: 'Leo Club of IIT', sponsor: 'Lions Club of Colombo 4', region: 'Region A', members: 55, president: 'Leo Lion Sithuli Amunuthuduwa', secretary: 'Leo V. Perera', treasurer: 'Leo W. Perera', advisor: 'Lion X. Perera', charteredDate: '2016-03-30', email: 'iitleoclub@gmail.com', phone: '+94 77 888 9999', facebook: '#', instagram: '#', linkedin: '#', desc: 'Pioneering technology hackathons, software donations, and digital literacy camps.', status: 'Active', displayOrder: 8, logo: null, banner: null },
  { id: 'cl-9', name: 'Leo Club of Moratuwa', sponsor: 'Lions Club of Moratuwa', region: 'Region B', members: 70, president: 'Leo Lion Nuran Nayanajith', secretary: 'Leo Y. Perera', treasurer: 'Leo Z. Perera', advisor: 'Lion AA. Perera', charteredDate: '1985-05-10', email: 'moratuwaleos@gmail.com', phone: '+94 77 999 0000', facebook: '#', instagram: '#', linkedin: '#', desc: 'One of the oldest community clubs committed to rural water supply and school support.', status: 'Active', displayOrder: 9, logo: null, banner: null },
  { id: 'cl-10', name: 'Leo Club of Moratuwa - Ratmalana', sponsor: 'Lions Club of Moratuwa Rathmalana', region: 'Region B', members: 40, president: 'Leo Senuja Kaluarachchi', secretary: 'Leo AB. Perera', treasurer: 'Leo AC. Perera', advisor: 'Lion AD. Perera', charteredDate: '2001-08-15', email: 'moratuwarathmalanaleos@gmail.com', phone: '+94 77 000 1111', facebook: '#', instagram: '#', linkedin: '#', desc: 'Spearheading regional medical clinics and youth skill development camps.', status: 'Active', displayOrder: 10, logo: null, banner: null },
  { id: 'cl-11', name: 'Leo Club of Moratuwa 2020', sponsor: 'Lions Club of Moratuwa 2020', region: 'Region B', members: 35, president: 'Leo Lion Pumudu Ramuditha', secretary: 'Leo AE. Perera', treasurer: 'Leo AF. Perera', advisor: 'Lion AG. Perera', charteredDate: '2020-02-20', email: 'moratuwa2020leos@gmail.com', phone: '+94 77 111 3333', facebook: '#', instagram: '#', linkedin: '#', desc: 'Committed to environment care, plastic recycling campaigns, and health camps.', status: 'Active', displayOrder: 11, logo: null, banner: null },
  { id: 'cl-12', name: 'Leo Club of Mount Lavinia Orient Centennial', sponsor: 'Lions Club of Dehiwala Mount Lavinia Orient', region: 'Region B', members: 32, president: 'Leo Minindu Witharana', secretary: 'Leo AH. Perera', treasurer: 'Leo AI. Perera', advisor: 'Lion AJ. Perera', charteredDate: '2016-06-18', email: 'mountlaviniaorientleos@gmail.com', phone: '+94 77 222 4444', facebook: '#', instagram: '#', linkedin: '#', desc: 'Designing community hygiene, sanitary supply drives, and kids literacy workshops.', status: 'Active', displayOrder: 12, logo: null, banner: null },
  { id: 'cl-13', name: 'Leo Club of Royal Achievers', sponsor: 'Lions Club of Panadura Heritage', region: 'Region B', members: 28, president: 'Leo Lion Geemeth Bodiyabadu', secretary: 'Leo AK. Perera', treasurer: 'Leo AL. Perera', advisor: 'Lion AM. Perera', charteredDate: '2018-09-05', email: 'royalachieversleos@gmail.com', phone: '+94 77 333 5555', facebook: '#', instagram: '#', linkedin: '#', desc: 'Active youth organizers of public service health checkups and book donations.', status: 'Active', displayOrder: 13, logo: null, banner: null },
  { id: 'cl-14', name: 'Leo Club of General Sir John Kotelawala Defence University', sponsor: 'Lions Club of Aluthgama Benthota', region: 'Region B', members: 50, president: 'Leo Mihin Senarathna', secretary: 'Leo AN. Perera', treasurer: 'Leo AO. Perera', advisor: 'Lion AP. Perera', charteredDate: '2015-11-12', email: 'kduleoclub@gmail.com', phone: '+94 77 444 6666', facebook: '#', instagram: '#', linkedin: '#', desc: 'Military university-based club designing disaster relief and command training sessions.', status: 'Active', displayOrder: 14, logo: null, banner: null },
  { id: 'cl-15', name: "Leo Club of Prince of Wales' College", sponsor: 'Lions Club of Moratuwa', region: 'Region B', members: 30, president: 'Leo Randidu Jayawardena', secretary: 'Leo AQ. Perera', treasurer: 'Leo AR. Perera', advisor: 'Lion AS. Perera', charteredDate: '2013-05-18', email: 'princeofwalesleos@gmail.com', phone: '+94 77 555 7777', facebook: '#', instagram: '#', linkedin: '#', desc: 'School alumni-based club targeting school resource development and child welfare.', status: 'Active', displayOrder: 15, logo: null, banner: null },
  { id: 'cl-16', name: "Leo Club of Princess of Wales' College", sponsor: 'Lions Club of Panadura Metro', region: 'Region B', members: 30, president: 'Leo Vinuri Aponso', secretary: 'Leo AT. Perera', treasurer: 'Leo AU. Perera', advisor: 'Lion AV. Perera', charteredDate: '2014-06-20', email: 'princessofwalesleos@gmail.com', phone: '+94 77 666 8888', facebook: '#', instagram: '#', linkedin: '#', desc: 'Empowering young women to drive sanitary health and child vision support programs.', status: 'Active', displayOrder: 16, logo: null, banner: null },
  { id: 'cl-17', name: 'Leo Club of Sri Sumangala College', sponsor: 'Lions Club of Panadura Heritage', region: 'Region B', members: 35, president: 'Leo Danidu Damsith', secretary: 'Leo AW. Perera', treasurer: 'Leo AX. Perera', advisor: 'Lion AY. Perera', charteredDate: '2012-03-10', email: 'srisumangalaleos@gmail.com', phone: '+94 77 777 9999', facebook: '#', instagram: '#', linkedin: '#', desc: 'Reuniting college students to coordinate village upliftment projects.', status: 'Active', displayOrder: 17, logo: null, banner: null },
  { id: 'cl-18', name: 'Leo Club of Kalutara Vidyalaya', sponsor: 'Lions Club of Kaluwamodara Moragalla', region: 'Region B', members: 28, president: 'Leo Ometh Nethsanda', secretary: 'Leo AZ. Perera', treasurer: 'Leo BA. Perera', advisor: 'Lion BB. Perera', charteredDate: '2017-07-07', email: 'kalutaravidyalayaleos@gmail.com', phone: '+94 77 888 0000', facebook: '#', instagram: '#', linkedin: '#', desc: 'Committed to disaster relief, mobile medical camps, and environment initiatives.', status: 'Active', displayOrder: 18, logo: null, banner: null },
  { id: 'cl-19', name: 'Leo Club of Kalutara Balika Vidyalaya', sponsor: 'Lions Club of Kalutara Central', region: 'Region B', members: 26, president: 'Leo Sethmi Sonaya', secretary: 'Leo BC. Perera', treasurer: 'Leo BD. Perera', advisor: 'Lion BE. Perera', charteredDate: '2019-09-09', email: 'kalutarabalikaleos@gmail.com', phone: '+94 77 999 1111', facebook: '#', instagram: '#', linkedin: '#', desc: 'Dedicated to young female leadership, library support, and village wellness camps.', status: 'Active', displayOrder: 19, logo: null, banner: null }
];

const SEED_CLUB_LOGOS = [
  { id: 'cl-logo-1', name: 'Leo Club of Royal Achievers', image: 'royal_achievers_logo.png', displayOrder: 1, status: 'Active', photoScale: 1, photoX: 50, photoY: 50, frameType: 'rectangle' },
  { id: 'cl-logo-2', name: 'Leo Club of Sri Sumangala College', image: 'sri_sumangala_logo.jpg', displayOrder: 2, status: 'Active', photoScale: 1, photoX: 50, photoY: 50, frameType: 'rectangle' }
];

const SEED_GOVERNORS = [
  { id: 'gov-1', name: "Leo Lion Yashika Rodrigo", year: "2025/2026", theme: "Leo Club of Mount Lavinia Orient Centennial", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 1, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-2', name: "Leo Lion Sajani Wijesuriya", year: "2024/2025", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 2, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-3', name: "Leo Lion Akila Gunarathne", year: "2023/2024", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 3, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-4', name: "Leo Lion Randhir Samarasinghe", year: "2022/2023", theme: "Leo Club of Colombo Millenium", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 4, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-5', name: "Leo Lion Gayanga Uththaravi Diaz", year: "2021/2022", theme: "Leo Club of Unawatuna Diamond Stars", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 5, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-6', name: "Leo Lion Malinda Ganewatta", year: "2020/2021", theme: "Leo Club of Colombo Millenium", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 6, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-7', name: "Leo Ochintha Nadeeshan", year: "2019/2020", theme: "Leo Club of Mount Lavinia Orient Centennial", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 7, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-8', name: "Leo Lion Dilshan Peiris", year: "2018/2019", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 8, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-9', name: "Lion Navodhya Jayasinghe", year: "2017/2018", theme: "Leo Club of University of Colombo Faculty of Science", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 9, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-10', name: "Lion Supun Dahanayake", year: "2016/2017", theme: "Leo Club of Unawatuna Diamond Stars", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 10, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-11', name: "Mr. Darshana Ranasinghe", year: "2015/2016", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 11, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-12', name: "Lion Sumudu Hewage", year: "2014/2015", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 12, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-13', name: "Mr. Anju Supun Panditharathne", year: "2013/2014", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 13, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-14', name: "Mrs. Vichalya Wijesuriya", year: "2012/2013", theme: "Leo Club of Moratuwa Orient", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 14, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-15', name: "Lion Fouzul Nilaufer", year: "2011/2012", theme: "Leo Club of Galle", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 15, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-16', name: "Mr. Dan De Silva", year: "2010/2011", theme: "Leo Club of Aluthgama Benthota", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 16, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-17', name: "Mrs. Shohana Wijesuriya", year: "2009/2010", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 17, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-18', name: "Lion Asitha Pinnaduwa MJF", year: "2008/2009", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 18, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-19', name: "Mr. Ricky Simms", year: "2007/2008", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 19, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-20', name: "Mrs. Dhshanthie Gamalatge", year: "2006/2007", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 20, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-21', name: "Mr. Late Nilanka Fernando", year: "2005/2006", theme: "Leo Club of Moratuwa-Rathmalana", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 21, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-22', name: "Mr. Kanishka Hewage", year: "2004/2005", theme: "Leo Club of Colombo Millenium", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 22, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-23', name: "Mr. Shehan Kumar", year: "2003/2004", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 23, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-24', name: "Lion Shyana Jayalath MJF, PMAF, PFLM", year: "2002/2003", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 24, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-25', name: "Mr. Charaka Perera", year: "2001/2002", theme: "Leo Club of Moratuwa-Rathmalana", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 25, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-26', name: "Lion Shavindra Diaz", year: "2000/2001", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 26, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-27', name: "Mr. Niroshan Silva", year: "1999/2000", theme: "Leo Club of Galkissa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 27, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-28', name: "Mrs. Kulani Wickramarathne", year: "1998/1999", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 28, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-29', name: "Mr. Azeem Azwar", year: "1997/1998", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 29, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-30', name: "Mr. Siraj Jabir", year: "1996/1997", theme: "Leo Club of Dehiwal North", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 30, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-31', name: "Mr. Sheron Fernando", year: "1995/1996", theme: "Leo Club of Moratuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 31, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-32', name: "Mr. Late Kanchana Wijerathne", year: "1994/1995", theme: "Leo Club of Moratuwa-Rathmalana", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 32, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-33', name: "Mrs. Shashikala Sinnathurai", year: "1993/1994", theme: "Leo Club of Kolpitya", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 33, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-34', name: "Mr. Janin Mudannayake", year: "1992/1993", theme: "Leo Club of Milagiriya", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 34, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-35', name: "Mr. Manoj Wickramathunga", year: "1991/1992", theme: "Leo Club of Wellawatta", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 35, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-36', name: "Riza Aziz", year: "1990/1991", theme: "Leo Club of Dehiwal North", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 36, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-37', name: "Mr. Prabath Wellaboda", year: "1990/1991", theme: "Leo Club of Boralesgamuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 37, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-38', name: "Mr. Harith Munasinghe", year: "1989/1990", theme: "Leo Club of Milagiriya", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 38, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-39', name: "Mr. Hemaka De Alwiz", year: "1988/1989", theme: "Leo Club of Mahanama College", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 39, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-40', name: "Mr. Aruna Kumarasinghe", year: "1988/1989", theme: "Leo Club of Boralesgamuwa", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 40, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-41', name: "Mr. Nimal Panditha Koralage", year: "1987/1988", theme: "Leo Club of Nugegoda Mid Town", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 41, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-42', name: "Mr. Hemaka Diaz", year: "1986/1987", theme: "Leo Club of Milagiriya", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 42, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-43', name: "Mr. Imithiaz Ismail", year: "1985/1986", theme: "Leo Club of Wellawatta", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 43, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-44', name: "Mr. Errol Abeyrathne", year: "1984/1985", theme: "Leo Club of Colombo West", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 44, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-45', name: "Mr. Harin Jayasekara", year: "1983/1984", theme: "Leo Club of Maharagama", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 45, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-46', name: "Mr. T.R.Jeganadan", year: "1982/1983", theme: "Leo Club of Maharagama", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 46, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-47', name: "Mr. Dilip Wazirani", year: "1981/1982", theme: "Leo Club of Colombo West", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 47, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-48', name: "Mr. Ruwan Rathnaweera", year: "1980/1981", theme: "Leo Club of Colombo North", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 48, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-49', name: "Mr. Mohan Burhan", year: "1979/1980", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 49, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-50', name: "Mr. Ghazzeli Mohideen", year: "1978/1979", theme: "Leo Club of Colombo West", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 50, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-51', name: "Mr. Arjun Mendis", year: "1978/1979", theme: "Leo Club of Nugegoda", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 51, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-52', name: "PCC Lion Sunil Dharmarathne", year: "1977/1978", theme: "Leo Club of Mattakkuliya", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 52, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-53', name: "Mr. Lalith C.N. Grero", year: "1976/1977", theme: "Leo Club of Colombo South", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 53, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-54', name: "Mr. Trevor Reckerman", year: "1975/1976", theme: "Leo Club of Wattala", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 54, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-55', name: "Mr. Azad Mohideen", year: "1974/1975", theme: "Leo Club of Moratuwa-Rathmalana", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 55, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-56', name: "Mr. T.Skantharajah", year: "1973/1974", theme: "Leo Club of Moratuwa-Rathmalana", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 56, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-57', name: "Mr. Bryan Wijekoon", year: "1972/1973", theme: "Leo Club of Colombo South", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 57, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'gov-58', name: "Mr. Dinal Jayamanne", year: "1971/1972", theme: "Leo Club of Colombo Host", logo: "fa-shield-halved", achievement: "", status: 'Active', displayOrder: 58, photo: null, photoScale: 1, photoX: 50, photoY: 50 }
];

const SEED_BLOGS = [
  { id: 'blog-1', title: "Leo District 306 D1 Kicks Off 2026 Service Year", date: "2026-07-01", author: "District Editorial Panel", content: "Our new service year has officially begun with a series of community support projects launched across multiple regions. Over 25 clubs joined hands to coordinate regional health camps and distribute essential supplies to schools in rural zones.", status: 'Active', displayOrder: 1, photo: null, photoScale: 1, photoX: 50, photoY: 50 },
  { id: 'blog-2', title: "Empowering Rural Schools: RO Water Project Reaches Completion", date: "2026-06-18", author: "Public Relations Chair", content: "Through a collaborated district effort, the installation of water purification and reverse osmosis systems in rural schools has successfully crossed 20 operational units, providing clean drinking water to thousands of students.", status: 'Active', displayOrder: 2, photo: null, photoScale: 1, photoX: 50, photoY: 50 }
];
